<a href="https://colab.research.google.com/github/ritvik-123/EMP-Project/blob/master/Current-Notebooks/Final_LogReg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# --- Imports -----------------------------------------------------------
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer

from sklearn.model_selection import GroupKFold
from sklearn.decomposition import TruncatedSVD         # dimensionality reduction (SVD works with dense/sparse)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score
)

from sklearn.metrics import top_k_accuracy_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split

import torch

In [ ]:
# --- Config --------------------------------------------------------------
CSV_PATH = "../Data/"

MODEL_PATH = "../Model/"   # your labeled sentence-level file

TARGET_LABELS = [                                # the 4 label columns we're predicting
    "ideological",
    "institutionalized",
    "interpersonal",
    "internalized",
]
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"  # 384-dim embedding model
N_SVD_COMPONENTS = 50                            # compress 384-dim embeddings down further before the classifier
N_FOLDS = 5                                      # number of GroupKFold splits (you could also use LeaveOneGroupOut)
RANDOM_STATE = 42                                # fixed seed so results are reproducible
THRESHOLD = 0.5                                  # probability cutoff for turning a score into a 0/1 prediction

%pwd
%cd /content/drive/MyDrive/EMP/Notebook

/content/drive/MyDrive/EMP/Notebook


In [ ]:
# --- Load -----------------------------------------------------------------
df = pd.read_csv(CSV_PATH + "Generated_Sentences_1.csv")

df_1 = pd.read_csv(CSV_PATH + "Module 1 Sentences Gemini.csv")

df_1 = df_1[['sentence','ideological','institutionalized','interpersonal','internalized','primary_leaning']]
df_1 = df_1[df_1['primary_leaning'] != 'none']
df_1 = df_1.reset_index(drop=True)
df_1 = df_1.rename(columns={'sentence':'Sentence'})
df_1 = df_1.rename(columns={'primary_leaning':'Label'})
df_1["data_source"] = "real world"

df = pd.concat([df, df_1], ignore_index=True)

# df = df[df['data_source'] != 'extra_institutionalized']

# Clean column names just in case there are spaces
df.columns = df.columns.str.strip()

print("Columns:", df.columns.tolist())

# Clean sentences
df["Sentence"] = df["Sentence"].fillna("").astype(str).str.strip()
df = df[df["Sentence"] != ""].reset_index(drop=True)

# Clean Label column
df["Label"] = df["Label"].fillna("").astype(str).str.strip().str.lower()

# Create the 4 target label columns from the single Label column
for label in TARGET_LABELS:
    df[label] = (df["Label"] == label).astype(int)

# Optional: create source_id if your new file does not have one
if "source_id" not in df.columns:
    df["source_id"] = df.index

print("Rows after cleaning:", len(df))
print("Unique groups (source_id):", df["source_id"].nunique())
print(df[TARGET_LABELS].sum())

Columns: ['Sentence', 'Label', 'data_source', 'ideological', 'institutionalized', 'interpersonal', 'internalized']
Rows after cleaning: 810
Unique groups (source_id): 810
ideological          203
institutionalized    256
interpersonal        195
internalized         156
dtype: int64


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

if device == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))

Device: cuda
GPU: Tesla T4


In [ ]:
# --- Embed ------------------------------------------------------------------
device = "cuda"   # change to "cpu" if you're not on a GPU runtime

embedder = SentenceTransformer(EMBEDDING_MODEL_NAME, device=device)   # loads the pretrained embedding model

sentences = df["Sentence"].tolist()                                   # plain list of strings to embed

X_full = embedder.encode(
    sentences,                     # the sentences to embed
    batch_size=32,                 # how many sentences to embed per forward pass
    normalize_embeddings=True,     # L2-normalize each embedding (helps cosine-similarity-style comparisons)
    show_progress_bar=True,        # display a progress bar since this can take a minute
    convert_to_numpy=True,         # return a numpy array instead of torch tensors
)

print("Embedding matrix shape:", X_full.shape)   # expect (num_sentences, 384)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/26 [00:00<?, ?it/s]

Embedding matrix shape: (810, 384)


In [ ]:
# ------------------------------------------------------------
# Train/test split BEFORE SVD + Logistic Regression
# ------------------------------------------------------------

y_full = df["Label"].values

X_train_embed, X_test_embed, y_train, y_test, df_train, df_test = train_test_split(
    X_full,
    y_full,
    df,
    test_size=0.2,
    random_state=RANDOM_STATE,
    stratify=y_full
)

print("Train shape:", X_train_embed.shape)
print("Test shape:", X_test_embed.shape)

Train shape: (648, 384)
Test shape: (162, 384)


In [ ]:
# ------------------------------------------------------------
# Sample weights for TRAINING rows only
# ------------------------------------------------------------

sample_weight = np.ones(len(df_train))

sample_weight[df_train["data_source"] == "base_synthetic"] = 1.0
sample_weight[df_train["data_source"] == "contrastive_synthetic"] = 1.0
sample_weight[df_train["data_source"] == "contrastive_synthetic_v2"] = 0.8
sample_weight[df_train["data_source"] == "extra_institutionalized"] = 1.0

In [ ]:
# ------------------------------------------------------------
# Fit SVD on train only, then transform train and test
# ------------------------------------------------------------

final_svd = TruncatedSVD(
    n_components=N_SVD_COMPONENTS,
    random_state=RANDOM_STATE
)

X_train = final_svd.fit_transform(X_train_embed)
X_test = final_svd.transform(X_test_embed)

In [ ]:
# ------------------------------------------------------------
# Train Logistic Regression
# ------------------------------------------------------------

final_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=0.5,
        max_iter=3000,
        solver="lbfgs",
        class_weight=None,
        random_state=RANDOM_STATE
    ))
])

final_clf.fit(
    X_train,
    y_train,
    logreg__sample_weight=sample_weight
)

print("Model trained on training split.")
print("Classes:", final_clf.named_steps["logreg"].classes_)

Model trained on training split.
Classes: ['ideological' 'institutionalized' 'internalized' 'interpersonal']


In [ ]:
# ------------------------------------------------------------
# Evaluate on test set
# ------------------------------------------------------------

y_pred = final_clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Macro F1:", f1_score(y_test, y_pred, average="macro"))

print("\nClassification report:")
print(classification_report(y_test, y_pred))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred, labels=final_clf.named_steps["logreg"].classes_))

Accuracy: 0.7777777777777778
Macro F1: 0.7685477097085618

Classification report:
                   precision    recall  f1-score   support

      ideological       0.71      0.66      0.68        41
institutionalized       0.90      0.86      0.88        51
     internalized       0.72      0.74      0.73        31
    interpersonal       0.74      0.82      0.78        39

         accuracy                           0.78       162
        macro avg       0.77      0.77      0.77       162
     weighted avg       0.78      0.78      0.78       162


Confusion matrix:
[[27  1  6  7]
 [ 5 44  1  1]
 [ 2  3 23  3]
 [ 4  1  2 32]]


In [ ]:
# ------------------------------------------------------------
# Evaluate Top-2 accuracy
# ------------------------------------------------------------

proba = final_clf.predict_proba(X_test)

classes = final_clf.named_steps["logreg"].classes_

top2_acc = top_k_accuracy_score(
    y_test,
    proba,
    k=2,
    labels=classes
)

print("Top-2 Accuracy:", top2_acc)

Top-2 Accuracy: 0.9629629629629629


In [ ]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

# ------------------------------------------------------------
# Hyperparameter tuning on TRAINING DATA ONLY
# ------------------------------------------------------------

tuning_pipe = Pipeline([
    ("svd", TruncatedSVD(random_state=RANDOM_STATE)),
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        max_iter=5000,
        solver="lbfgs",
        random_state=RANDOM_STATE
    ))
])

param_grid = {
    "svd__n_components": [30, 50, 75, 100, 150, 200],
    "logreg__C": [0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0],
    "logreg__class_weight": [None, "balanced"]
}

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

grid = GridSearchCV(
    estimator=tuning_pipe,
    param_grid=param_grid,
    scoring="f1_macro",
    cv=cv,
    n_jobs=-1,
    verbose=2
)

grid.fit(
    X_train_embed,
    y_train,
    logreg__sample_weight=sample_weight
)

print("Best CV Macro F1:", grid.best_score_)
print("Best params:", grid.best_params_)

Fitting 5 folds for each of 84 candidates, totalling 420 fits
Best CV Macro F1: 0.825072161028579
Best params: {'logreg__C': 0.2, 'logreg__class_weight': None, 'svd__n_components': 50}


In [ ]:
# ------------------------------------------------------------
# Evaluate best tuned model on untouched test set
# ------------------------------------------------------------

best_clf = grid.best_estimator_

y_pred_best = best_clf.predict(X_test_embed)
proba_best = best_clf.predict_proba(X_test_embed)

classes_best = best_clf.named_steps["logreg"].classes_

print("Accuracy:", accuracy_score(y_test, y_pred_best))
print("Macro F1:", f1_score(y_test, y_pred_best, average="macro"))

print("Top-2 Accuracy:", top_k_accuracy_score(
    y_test,
    proba_best,
    k=2,
    labels=classes_best
))

print("\nClassification report:")
print(classification_report(y_test, y_pred_best))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred_best, labels=classes_best))

Accuracy: 0.7777777777777778
Macro F1: 0.7677639937831673
Top-2 Accuracy: 0.9444444444444444

Classification report:
                   precision    recall  f1-score   support

      ideological       0.71      0.66      0.68        41
institutionalized       0.88      0.88      0.88        51
     internalized       0.72      0.74      0.73        31
    interpersonal       0.76      0.79      0.78        39

         accuracy                           0.78       162
        macro avg       0.77      0.77      0.77       162
     weighted avg       0.78      0.78      0.78       162


Confusion matrix:
[[27  1  6  7]
 [ 5 45  1  0]
 [ 2  3 23  3]
 [ 4  2  2 31]]


In [ ]:
# ------------------------------------------------------------
# Logistic Regression without SVD
# ------------------------------------------------------------

no_svd_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=0.5,
        max_iter=5000,
        solver="lbfgs",
        class_weight=None,
        random_state=RANDOM_STATE
    ))
])

no_svd_clf.fit(
    X_train_embed,
    y_train,
    logreg__sample_weight=sample_weight
)

y_pred_no_svd = no_svd_clf.predict(X_test_embed)
proba_no_svd = no_svd_clf.predict_proba(X_test_embed)

classes_no_svd = no_svd_clf.named_steps["logreg"].classes_

print("No SVD Accuracy:", accuracy_score(y_test, y_pred_no_svd))
print("No SVD Macro F1:", f1_score(y_test, y_pred_no_svd, average="macro"))
print("No SVD Top-2 Accuracy:", top_k_accuracy_score(
    y_test,
    proba_no_svd,
    k=2,
    labels=classes_no_svd
))

No SVD Accuracy: 0.7901234567901234
No SVD Macro F1: 0.7746549941697621
No SVD Top-2 Accuracy: 0.9444444444444444


In [ ]:
from sklearn.calibration import CalibratedClassifierCV

# ------------------------------------------------------------
# Calibrated Logistic Regression
# ------------------------------------------------------------

base_clf = Pipeline([
    ("svd", TruncatedSVD(
        n_components=grid.best_params_["svd__n_components"],
        random_state=RANDOM_STATE
    )),
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=grid.best_params_["logreg__C"],
        max_iter=5000,
        solver="lbfgs",
        class_weight=grid.best_params_["logreg__class_weight"],
        random_state=RANDOM_STATE
    ))
])

calibrated_clf = CalibratedClassifierCV(
    estimator=base_clf,
    method="sigmoid",
    cv=5
)

calibrated_clf.fit(
    X_train_embed,
    y_train,
    logreg__sample_weight=sample_weight
)

y_pred_cal = calibrated_clf.predict(X_test_embed)
proba_cal = calibrated_clf.predict_proba(X_test_embed)

print("Calibrated Accuracy:", accuracy_score(y_test, y_pred_cal))
print("Calibrated Macro F1:", f1_score(y_test, y_pred_cal, average="macro"))
print("Calibrated Top-2 Accuracy:", top_k_accuracy_score(
    y_test,
    proba_cal,
    k=2,
    labels=calibrated_clf.classes_
))

Calibrated Accuracy: 0.7962962962962963
Calibrated Macro F1: 0.7873583733339831
Calibrated Top-2 Accuracy: 0.9506172839506173


In [ ]:
def predict_with_top2(sentence, embedder, clf):
    embedding = embedder.encode(
        [sentence],
        normalize_embeddings=True,
        convert_to_numpy=True
    )

    proba = clf.predict_proba(embedding)[0]
    classes = clf.classes_ if hasattr(clf, "classes_") else clf.named_steps["logreg"].classes_

    top2_idx = np.argsort(proba)[-2:][::-1]

    top1_label = classes[top2_idx[0]]
    top2_label = classes[top2_idx[1]]

    top1_prob = proba[top2_idx[0]]
    top2_prob = proba[top2_idx[1]]

    margin = top1_prob - top2_prob

    result = {
        "top1_label": top1_label,
        "top1_prob": float(top1_prob),
        "top2_label": top2_label,
        "top2_prob": float(top2_prob),
        "margin": float(margin)
    }

    return result

In [ ]:
result = predict_with_top2(
    "I started believing I was less capable because of how people treated me.",
    embedder,
    best_clf
)

result

{'top1_label': 'internalized',
 'top1_prob': 0.9638246155251273,
 'top2_label': 'interpersonal',
 'top2_prob': 0.019998462477383468,
 'margin': 0.9438261530477439}

In [ ]:
result = predict_with_top2(
    "The historic practice of redlining by major banks systematically denied mortgages to minority applicants, trapping generations of families in underfunded neighborhoods.",
    embedder,
    best_clf
)

result

{'top1_label': 'institutionalized',
 'top1_prob': 0.9984932194868343,
 'top2_label': 'interpersonal',
 'top2_prob': 0.0008719645026404072,
 'margin': 0.997621254984194}

In [ ]:
result = predict_with_top2(
    "The cultural myth of the 'model minority' places immense psychological pressure on Asian Americans while simultaneously being used to mask systemic racism and invalidate the struggles of other marginalized groups.",
    embedder,
    best_clf
)

result

{'top1_label': 'ideological',
 'top1_prob': 0.7835517525039855,
 'top2_label': 'institutionalized',
 'top2_prob': 0.20145387315649094,
 'margin': 0.5820978793474945}

In [ ]:
result = predict_with_top2(
    "A talented student from a working-class background who refuses to apply for a prestigious scholarship because they believe people from their neighborhood 'don't belong' at elite universities.",
    embedder,
    best_clf
)

result

{'top1_label': 'ideological',
 'top1_prob': 0.49478318605681526,
 'top2_label': 'institutionalized',
 'top2_prob': 0.40571492542812704,
 'margin': 0.08906826062868822}

In [ ]:
# ------------------------------------------------------------
# Confidence-only threshold analysis
# ------------------------------------------------------------

proba = final_clf.predict_proba(X_test)
classes = final_clf.named_steps["logreg"].classes_

top1_idx = np.argmax(proba, axis=1)
top1_labels = classes[top1_idx]
top1_probs = proba[np.arange(len(proba)), top1_idx]

correct = top1_labels == y_test

rows = []

for threshold in [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85]:
    use_logreg = top1_probs >= threshold
    use_llm = ~use_logreg

    if use_logreg.sum() == 0:
        continue

    rows.append({
        "threshold": threshold,
        "logreg_kept_percent": use_logreg.mean(),
        "llm_fallback_percent": use_llm.mean(),
        "logreg_accuracy_when_kept": correct[use_logreg].mean(),
        "num_logreg": use_logreg.sum(),
        "num_llm": use_llm.sum()
    })

threshold_df = pd.DataFrame(rows)
threshold_df

,threshold,logreg_kept_percent,llm_fallback_percent,logreg_accuracy_when_kept,num_logreg,num_llm
0,0.50,0.938272,0.061728,0.809211,152,10
1,0.55,0.888889,0.111111,0.812500,144,18
2,0.60,0.833333,0.166667,0.837037,135,27
3,0.65,0.777778,0.222222,0.865079,126,36
4,0.70,0.728395,0.271605,0.889831,118,44
5,0.75,0.697531,0.302469,0.884956,113,49
6,0.80,0.611111,0.388889,0.919192,99,63
7,0.85,0.524691,0.475309,0.952941,85,77


In [ ]:
# ------------------------------------------------------------
# Inspect rows that would go to LLM
# ------------------------------------------------------------

CONF_THRESHOLD = 0.75

use_llm = top1_probs < CONF_THRESHOLD

df_fallback = df_test.copy().reset_index(drop=True)
df_fallback["true_label"] = y_test
df_fallback["logreg_pred"] = top1_labels
df_fallback["logreg_confidence"] = top1_probs
df_fallback["logreg_correct"] = correct

df_fallback_cases = df_fallback[use_llm].copy()

df_fallback_cases[[
    "Sentence",
    "true_label",
    "logreg_pred",
    "logreg_confidence",
    "logreg_correct",
    "data_source"
]].sort_values("logreg_confidence")

,Sentence,true_label,logreg_pred,logreg_confidence,logreg_correct,data_source
115,I caught myself thinking that the student who ...,ideological,ideological,0.360714,True,contrastive_synthetic
133,"By holding onto deficit narratives, I've been ...",interpersonal,interpersonal,0.423021,True,contrastive_synthetic
32,A highlight: I noticed that pretty much all of...,institutionalized,ideological,0.431265,False,real world
34,"Telling the student that their artwork was ""to...",ideological,interpersonal,0.435967,False,contrastive_synthetic
122,I soon learned to see color.,ideological,interpersonal,0.454702,False,real world
118,I hold privilege as a person with a college de...,ideological,interpersonal,0.468268,False,real world
25,I avoided mirrors because I had absorbed messa...,internalized,interpersonal,0.491904,False,base_synthetic
141,"However, I never considered it privilege!",internalized,ideological,0.494806,False,real world
144,He told me I was “brave” for going out in publ...,interpersonal,interpersonal,0.497985,True,base_synthetic
108,I find myself giving generic advice to my ment...,institutionalized,interpersonal,0.498851,False,extra_institutionalized


In [ ]:
df_fallback_cases["llm_pred"] = None

In [ ]:
# ------------------------------------------------------------
# Train FINAL production model on ALL data and save artifacts
# ------------------------------------------------------------

import os
import json
import joblib

ARTIFACT_DIR = "../Model/logreg_artifacts"
os.makedirs(ARTIFACT_DIR, exist_ok=True)

# Labels
y_prod = df["Label"].values

# Sample weights for all rows
prod_sample_weight = np.ones(len(df))

prod_sample_weight[df["data_source"] == "base_synthetic"] = 1.0
prod_sample_weight[df["data_source"] == "contrastive_synthetic"] = 1.0
prod_sample_weight[df["data_source"] == "contrastive_synthetic_v2"] = 0.8
prod_sample_weight[df["data_source"] == "extra_institutionalized"] = 1.0
prod_sample_weight[df["data_source"] == "real world"] = 1.0

# Fit SVD on all embedded data
prod_svd = TruncatedSVD(
    n_components=N_SVD_COMPONENTS,
    random_state=RANDOM_STATE
)

X_prod = prod_svd.fit_transform(X_full)

# Fit final classifier on all data
prod_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=0.5,
        max_iter=3000,
        solver="lbfgs",
        class_weight=None,
        random_state=RANDOM_STATE
    ))
])

prod_clf.fit(
    X_prod,
    y_prod,
    logreg__sample_weight=prod_sample_weight
)

# Save artifacts
joblib.dump(prod_svd, f"{ARTIFACT_DIR}/svd.joblib")
joblib.dump(prod_clf, f"{ARTIFACT_DIR}/logreg_pipeline.joblib")

metadata = {
    "embedding_model_name": EMBEDDING_MODEL_NAME,
    "n_svd_components": N_SVD_COMPONENTS,
    "confidence_threshold": 0.75,
    "labels": list(prod_clf.named_steps["logreg"].classes_),
    "random_state": RANDOM_STATE
}

with open(f"{ARTIFACT_DIR}/metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)

print("Production artifacts saved to:", ARTIFACT_DIR)
print("Classes:", prod_clf.named_steps["logreg"].classes_)

Production artifacts saved to: ../Model/logreg_artifacts
Classes: ['ideological' 'institutionalized' 'internalized' 'interpersonal']


In [ ]:
# commiting from colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cd /content
!git clone https://github.com/ritvik-123/EMP-Project.git

/content
fatal: destination path 'EMP-Project' already exists and is not an empty directory.


In [ ]:
%cd /content/EMP-Project/

/content/EMP-Project


In [ ]:
# Create artifact folder in repo
!mkdir -p Model/logreg_artifacts

# Copy updated artifacts from Google Drive into repo
!cp -r /content/drive/MyDrive/EMP/Model/logreg_artifacts/* Model/logreg_artifacts/

In [ ]:
!ls -lh Model/logreg_artifacts

total 92K
-rw------- 1 root root 4.3K Jul 22 04:10 logreg_pipeline.joblib
-rw------- 1 root root  253 Jul 22 04:10 metadata.json
-rw------- 1 root root  77K Jul 22 04:10 svd.joblib


In [ ]:
!git config --global user.email "ritvik.mahapatra@yahoo.com"
!git config --global user.name "ritvik-123"

In [ ]:
!git add .
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   Model/logreg_artifacts/logreg_pipeline.joblib
	modified:   Model/logreg_artifacts/metadata.json
	modified:   Model/logreg_artifacts/svd.joblib



In [ ]:
from getpass import getpass
token = getpass("Paste GitHub token: ")

Paste GitHub token: ··········


In [ ]:
!git remote set-url origin https://ritvik-123:{token}@github.com/ritvik-123/EMP-Project.git
!git push origin master
!git remote set-url origin https://github.com/ritvik-123/EMP-Project.git

Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 74.82 KiB | 5.75 MiB/s, done.
Total 7 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/ritvik-123/EMP-Project.git
   75f84a2..d553d96  master -> master


In [ ]:
!git status
!git log --oneline -3

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
d553d96 (HEAD -> master, origin/master, origin/HEAD) Use smaller embedding model for Render deployment
75f84a2 Created using Colab
7c7bfe8 Merge pull request #2 from ritvik-123/cleanup-project-structure
