<a href="https://colab.research.google.com/github/ritvik-123/EMP-Project/blob/master/Current-Notebooks/Final_LogReg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# --- Imports -----------------------------------------------------------
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer

from sklearn.model_selection import GroupKFold
from sklearn.decomposition import TruncatedSVD         # dimensionality reduction (SVD works with dense/sparse)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score
)

from sklearn.metrics import top_k_accuracy_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split

import torch

In [3]:
# --- Config --------------------------------------------------------------
CSV_PATH = "../Data/"

MODEL_PATH = "../Model/"   # your labeled sentence-level file

TARGET_LABELS = [                                # the 4 label columns we're predicting
    "ideological",
    "institutionalized",
    "interpersonal",
    "internalized",
]
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"  # 384-dim embedding model
N_SVD_COMPONENTS = 50                            # compress 384-dim embeddings down further before the classifier
N_FOLDS = 5                                      # number of GroupKFold splits (you could also use LeaveOneGroupOut)
RANDOM_STATE = 42                                # fixed seed so results are reproducible
THRESHOLD = 0.5                                  # probability cutoff for turning a score into a 0/1 prediction

%pwd
%cd /content/drive/MyDrive/EMP/Notebook

/content/drive/MyDrive/EMP/Notebook


In [4]:
# --- Load -----------------------------------------------------------------
df = pd.read_csv(CSV_PATH + "Generated_Sentences_1.csv")

df_1 = pd.read_csv(CSV_PATH + "Module 1 Sentences Gemini.csv")

df_1 = df_1[['sentence','ideological','institutionalized','interpersonal','internalized','primary_leaning']]
df_1 = df_1[df_1['primary_leaning'] != 'none']
df_1 = df_1.reset_index(drop=True)
df_1 = df_1.rename(columns={'sentence':'Sentence'})
df_1 = df_1.rename(columns={'primary_leaning':'Label'})
df_1["data_source"] = "real world"

df = pd.concat([df, df_1], ignore_index=True)

# df = df[df['data_source'] != 'extra_institutionalized']

# Clean column names just in case there are spaces
df.columns = df.columns.str.strip()

print("Columns:", df.columns.tolist())

# Clean sentences
df["Sentence"] = df["Sentence"].fillna("").astype(str).str.strip()
df = df[df["Sentence"] != ""].reset_index(drop=True)

# Clean Label column
df["Label"] = df["Label"].fillna("").astype(str).str.strip().str.lower()

# Create the 4 target label columns from the single Label column
for label in TARGET_LABELS:
    df[label] = (df["Label"] == label).astype(int)

# Optional: create source_id if your new file does not have one
if "source_id" not in df.columns:
    df["source_id"] = df.index

print("Rows after cleaning:", len(df))
print("Unique groups (source_id):", df["source_id"].nunique())
print(df[TARGET_LABELS].sum())

Columns: ['Sentence', 'Label', 'data_source', 'ideological', 'institutionalized', 'interpersonal', 'internalized']
Rows after cleaning: 810
Unique groups (source_id): 810
ideological          203
institutionalized    256
interpersonal        195
internalized         156
dtype: int64


In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

if device == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))

Device: cuda
GPU: Tesla T4


In [6]:
# --- Embed ------------------------------------------------------------------
device = "cuda"   # change to "cpu" if you're not on a GPU runtime

embedder = SentenceTransformer(EMBEDDING_MODEL_NAME, device=device)   # loads the pretrained embedding model

sentences = df["Sentence"].tolist()                                   # plain list of strings to embed

X_full = embedder.encode(
    sentences,                     # the sentences to embed
    batch_size=32,                 # how many sentences to embed per forward pass
    normalize_embeddings=True,     # L2-normalize each embedding (helps cosine-similarity-style comparisons)
    show_progress_bar=True,        # display a progress bar since this can take a minute
    convert_to_numpy=True,         # return a numpy array instead of torch tensors
)

print("Embedding matrix shape:", X_full.shape)   # expect (num_sentences, 384)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.34GB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Batches:   0%|          | 0/26 [00:00<?, ?it/s]

Embedding matrix shape: (810, 1024)


In [7]:
# ------------------------------------------------------------
# Train/test split BEFORE SVD + Logistic Regression
# ------------------------------------------------------------

y_full = df["Label"].values

X_train_embed, X_test_embed, y_train, y_test, df_train, df_test = train_test_split(
    X_full,
    y_full,
    df,
    test_size=0.2,
    random_state=RANDOM_STATE,
    stratify=y_full
)

print("Train shape:", X_train_embed.shape)
print("Test shape:", X_test_embed.shape)

Train shape: (648, 1024)
Test shape: (162, 1024)


In [8]:
# ------------------------------------------------------------
# Sample weights for TRAINING rows only
# ------------------------------------------------------------

sample_weight = np.ones(len(df_train))

sample_weight[df_train["data_source"] == "base_synthetic"] = 1.0
sample_weight[df_train["data_source"] == "contrastive_synthetic"] = 1.0
sample_weight[df_train["data_source"] == "contrastive_synthetic_v2"] = 0.8
sample_weight[df_train["data_source"] == "extra_institutionalized"] = 1.0

In [9]:
# ------------------------------------------------------------
# Fit SVD on train only, then transform train and test
# ------------------------------------------------------------

final_svd = TruncatedSVD(
    n_components=N_SVD_COMPONENTS,
    random_state=RANDOM_STATE
)

X_train = final_svd.fit_transform(X_train_embed)
X_test = final_svd.transform(X_test_embed)

In [10]:
# ------------------------------------------------------------
# Train Logistic Regression
# ------------------------------------------------------------

final_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=0.5,
        max_iter=3000,
        solver="lbfgs",
        class_weight=None,
        random_state=RANDOM_STATE
    ))
])

final_clf.fit(
    X_train,
    y_train,
    logreg__sample_weight=sample_weight
)

print("Model trained on training split.")
print("Classes:", final_clf.named_steps["logreg"].classes_)

Model trained on training split.
Classes: ['ideological' 'institutionalized' 'internalized' 'interpersonal']


In [11]:
# ------------------------------------------------------------
# Evaluate on test set
# ------------------------------------------------------------

y_pred = final_clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Macro F1:", f1_score(y_test, y_pred, average="macro"))

print("\nClassification report:")
print(classification_report(y_test, y_pred))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred, labels=final_clf.named_steps["logreg"].classes_))

Accuracy: 0.8518518518518519
Macro F1: 0.8448306806515762

Classification report:
                   precision    recall  f1-score   support

      ideological       0.75      0.73      0.74        41
institutionalized       0.98      0.92      0.95        51
     internalized       0.75      0.87      0.81        31
    interpersonal       0.89      0.87      0.88        39

         accuracy                           0.85       162
        macro avg       0.84      0.85      0.84       162
     weighted avg       0.86      0.85      0.85       162


Confusion matrix:
[[30  1  7  3]
 [ 4 47  0  0]
 [ 3  0 27  1]
 [ 3  0  2 34]]


In [12]:
# ------------------------------------------------------------
# Evaluate Top-2 accuracy
# ------------------------------------------------------------

proba = final_clf.predict_proba(X_test)

classes = final_clf.named_steps["logreg"].classes_

top2_acc = top_k_accuracy_score(
    y_test,
    proba,
    k=2,
    labels=classes
)

print("Top-2 Accuracy:", top2_acc)

Top-2 Accuracy: 0.9753086419753086


In [13]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

# ------------------------------------------------------------
# Hyperparameter tuning on TRAINING DATA ONLY
# ------------------------------------------------------------

tuning_pipe = Pipeline([
    ("svd", TruncatedSVD(random_state=RANDOM_STATE)),
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        max_iter=5000,
        solver="lbfgs",
        random_state=RANDOM_STATE
    ))
])

param_grid = {
    "svd__n_components": [30, 50, 75, 100, 150, 200],
    "logreg__C": [0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0],
    "logreg__class_weight": [None, "balanced"]
}

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

grid = GridSearchCV(
    estimator=tuning_pipe,
    param_grid=param_grid,
    scoring="f1_macro",
    cv=cv,
    n_jobs=-1,
    verbose=2
)

grid.fit(
    X_train_embed,
    y_train,
    logreg__sample_weight=sample_weight
)

print("Best CV Macro F1:", grid.best_score_)
print("Best params:", grid.best_params_)

Fitting 5 folds for each of 84 candidates, totalling 420 fits
Best CV Macro F1: 0.8735192565498204
Best params: {'logreg__C': 0.05, 'logreg__class_weight': None, 'svd__n_components': 150}


In [14]:
# ------------------------------------------------------------
# Evaluate best tuned model on untouched test set
# ------------------------------------------------------------

best_clf = grid.best_estimator_

y_pred_best = best_clf.predict(X_test_embed)
proba_best = best_clf.predict_proba(X_test_embed)

classes_best = best_clf.named_steps["logreg"].classes_

print("Accuracy:", accuracy_score(y_test, y_pred_best))
print("Macro F1:", f1_score(y_test, y_pred_best, average="macro"))

print("Top-2 Accuracy:", top_k_accuracy_score(
    y_test,
    proba_best,
    k=2,
    labels=classes_best
))

print("\nClassification report:")
print(classification_report(y_test, y_pred_best))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred_best, labels=classes_best))

Accuracy: 0.8209876543209876
Macro F1: 0.8120765521398433
Top-2 Accuracy: 0.9691358024691358

Classification report:
                   precision    recall  f1-score   support

      ideological       0.71      0.66      0.68        41
institutionalized       0.96      0.92      0.94        51
     internalized       0.69      0.87      0.77        31
    interpersonal       0.89      0.82      0.85        39

         accuracy                           0.82       162
        macro avg       0.81      0.82      0.81       162
     weighted avg       0.83      0.82      0.82       162


Confusion matrix:
[[27  2  9  3]
 [ 2 47  2  0]
 [ 3  0 27  1]
 [ 6  0  1 32]]


In [15]:
# ------------------------------------------------------------
# Logistic Regression without SVD
# ------------------------------------------------------------

no_svd_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=0.5,
        max_iter=5000,
        solver="lbfgs",
        class_weight=None,
        random_state=RANDOM_STATE
    ))
])

no_svd_clf.fit(
    X_train_embed,
    y_train,
    logreg__sample_weight=sample_weight
)

y_pred_no_svd = no_svd_clf.predict(X_test_embed)
proba_no_svd = no_svd_clf.predict_proba(X_test_embed)

classes_no_svd = no_svd_clf.named_steps["logreg"].classes_

print("No SVD Accuracy:", accuracy_score(y_test, y_pred_no_svd))
print("No SVD Macro F1:", f1_score(y_test, y_pred_no_svd, average="macro"))
print("No SVD Top-2 Accuracy:", top_k_accuracy_score(
    y_test,
    proba_no_svd,
    k=2,
    labels=classes_no_svd
))

No SVD Accuracy: 0.8271604938271605
No SVD Macro F1: 0.8150408889677165
No SVD Top-2 Accuracy: 0.9753086419753086


In [16]:
from sklearn.calibration import CalibratedClassifierCV

# ------------------------------------------------------------
# Calibrated Logistic Regression
# ------------------------------------------------------------

base_clf = Pipeline([
    ("svd", TruncatedSVD(
        n_components=grid.best_params_["svd__n_components"],
        random_state=RANDOM_STATE
    )),
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=grid.best_params_["logreg__C"],
        max_iter=5000,
        solver="lbfgs",
        class_weight=grid.best_params_["logreg__class_weight"],
        random_state=RANDOM_STATE
    ))
])

calibrated_clf = CalibratedClassifierCV(
    estimator=base_clf,
    method="sigmoid",
    cv=5
)

calibrated_clf.fit(
    X_train_embed,
    y_train,
    logreg__sample_weight=sample_weight
)

y_pred_cal = calibrated_clf.predict(X_test_embed)
proba_cal = calibrated_clf.predict_proba(X_test_embed)

print("Calibrated Accuracy:", accuracy_score(y_test, y_pred_cal))
print("Calibrated Macro F1:", f1_score(y_test, y_pred_cal, average="macro"))
print("Calibrated Top-2 Accuracy:", top_k_accuracy_score(
    y_test,
    proba_cal,
    k=2,
    labels=calibrated_clf.classes_
))

Calibrated Accuracy: 0.8271604938271605
Calibrated Macro F1: 0.8147696931419736
Calibrated Top-2 Accuracy: 0.9753086419753086


In [17]:
def predict_with_top2(sentence, embedder, clf):
    embedding = embedder.encode(
        [sentence],
        normalize_embeddings=True,
        convert_to_numpy=True
    )

    proba = clf.predict_proba(embedding)[0]
    classes = clf.classes_ if hasattr(clf, "classes_") else clf.named_steps["logreg"].classes_

    top2_idx = np.argsort(proba)[-2:][::-1]

    top1_label = classes[top2_idx[0]]
    top2_label = classes[top2_idx[1]]

    top1_prob = proba[top2_idx[0]]
    top2_prob = proba[top2_idx[1]]

    margin = top1_prob - top2_prob

    result = {
        "top1_label": top1_label,
        "top1_prob": float(top1_prob),
        "top2_label": top2_label,
        "top2_prob": float(top2_prob),
        "margin": float(margin)
    }

    return result

In [18]:
result = predict_with_top2(
    "I started believing I was less capable because of how people treated me.",
    embedder,
    best_clf
)

result

{'top1_label': 'interpersonal',
 'top1_prob': 0.5165428015485243,
 'top2_label': 'internalized',
 'top2_prob': 0.4406003820690094,
 'margin': 0.07594241947951486}

In [19]:
result = predict_with_top2(
    "The historic practice of redlining by major banks systematically denied mortgages to minority applicants, trapping generations of families in underfunded neighborhoods.",
    embedder,
    best_clf
)

result

{'top1_label': 'institutionalized',
 'top1_prob': 0.9943352310684986,
 'top2_label': 'internalized',
 'top2_prob': 0.0021094880751017417,
 'margin': 0.9922257429933969}

In [20]:
result = predict_with_top2(
    "The cultural myth of the 'model minority' places immense psychological pressure on Asian Americans while simultaneously being used to mask systemic racism and invalidate the struggles of other marginalized groups.",
    embedder,
    best_clf
)

result

{'top1_label': 'ideological',
 'top1_prob': 0.9426492977522043,
 'top2_label': 'institutionalized',
 'top2_prob': 0.02846571058245376,
 'margin': 0.9141835871697506}

In [21]:
result = predict_with_top2(
    "A talented student from a working-class background who refuses to apply for a prestigious scholarship because they believe people from their neighborhood 'don't belong' at elite universities.",
    embedder,
    best_clf
)

result

{'top1_label': 'interpersonal',
 'top1_prob': 0.41919594741377364,
 'top2_label': 'ideological',
 'top2_prob': 0.317028915235124,
 'margin': 0.10216703217864964}

In [22]:
# ------------------------------------------------------------
# Confidence-only threshold analysis
# ------------------------------------------------------------

proba = final_clf.predict_proba(X_test)
classes = final_clf.named_steps["logreg"].classes_

top1_idx = np.argmax(proba, axis=1)
top1_labels = classes[top1_idx]
top1_probs = proba[np.arange(len(proba)), top1_idx]

correct = top1_labels == y_test

rows = []

for threshold in [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85]:
    use_logreg = top1_probs >= threshold
    use_llm = ~use_logreg

    if use_logreg.sum() == 0:
        continue

    rows.append({
        "threshold": threshold,
        "logreg_kept_percent": use_logreg.mean(),
        "llm_fallback_percent": use_llm.mean(),
        "logreg_accuracy_when_kept": correct[use_logreg].mean(),
        "num_logreg": use_logreg.sum(),
        "num_llm": use_llm.sum()
    })

threshold_df = pd.DataFrame(rows)
threshold_df

,threshold,logreg_kept_percent,llm_fallback_percent,logreg_accuracy_when_kept,num_logreg,num_llm
0,0.50,0.969136,0.030864,0.859873,157,5
1,0.55,0.925926,0.074074,0.860000,150,12
2,0.60,0.870370,0.129630,0.886525,141,21
3,0.65,0.833333,0.166667,0.903704,135,27
4,0.70,0.802469,0.197531,0.915385,130,32
5,0.75,0.777778,0.222222,0.936508,126,36
6,0.80,0.722222,0.277778,0.948718,117,45
7,0.85,0.641975,0.358025,0.961538,104,58


In [23]:
# ------------------------------------------------------------
# Inspect rows that would go to LLM
# ------------------------------------------------------------

CONF_THRESHOLD = 0.75

use_llm = top1_probs < CONF_THRESHOLD

df_fallback = df_test.copy().reset_index(drop=True)
df_fallback["true_label"] = y_test
df_fallback["logreg_pred"] = top1_labels
df_fallback["logreg_confidence"] = top1_probs
df_fallback["logreg_correct"] = correct

df_fallback_cases = df_fallback[use_llm].copy()

df_fallback_cases[[
    "Sentence",
    "true_label",
    "logreg_pred",
    "logreg_confidence",
    "logreg_correct",
    "data_source"
]].sort_values("logreg_confidence")

,Sentence,true_label,logreg_pred,logreg_confidence,logreg_correct,data_source
122,I soon learned to see color.,ideological,ideological,0.342399,True,real world
151,The placement test decided my math level witho...,institutionalized,institutionalized,0.343094,True,contrastive_synthetic_v2
15,She assumed the Latina nurse was there to tran...,interpersonal,ideological,0.444550,False,base_synthetic
100,When I got annoyed at the side-chatter during ...,ideological,interpersonal,0.473768,False,contrastive_synthetic
5,My friend was told he did not seem “gay enough...,interpersonal,interpersonal,0.488974,True,base_synthetic
126,I started thinking maybe I only got accepted b...,internalized,internalized,0.501767,True,contrastive_synthetic_v2
66,I think about how this impacted me growing up ...,internalized,internalized,0.502267,True,real world
134,People often assume that women who choose not ...,ideological,ideological,0.504308,True,base_synthetic
128,I hear jokes that make it seem normal for some...,ideological,ideological,0.514074,True,contrastive_synthetic_v2
149,Assessing participation based solely on vocal ...,institutionalized,institutionalized,0.518674,True,extra_institutionalized


In [24]:
df_fallback_cases["llm_pred"] = None

In [25]:
# ------------------------------------------------------------
# Train FINAL production model on ALL data and save artifacts
# ------------------------------------------------------------

import os
import json
import joblib

ARTIFACT_DIR = "../Model/logreg_artifacts"
os.makedirs(ARTIFACT_DIR, exist_ok=True)

# Labels
y_prod = df["Label"].values

# Sample weights for all rows
prod_sample_weight = np.ones(len(df))

prod_sample_weight[df["data_source"] == "base_synthetic"] = 1.0
prod_sample_weight[df["data_source"] == "contrastive_synthetic"] = 1.0
prod_sample_weight[df["data_source"] == "contrastive_synthetic_v2"] = 0.8
prod_sample_weight[df["data_source"] == "extra_institutionalized"] = 1.0
prod_sample_weight[df["data_source"] == "real world"] = 1.0

# Fit SVD on all embedded data
prod_svd = TruncatedSVD(
    n_components=N_SVD_COMPONENTS,
    random_state=RANDOM_STATE
)

X_prod = prod_svd.fit_transform(X_full)

# Fit final classifier on all data
prod_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=0.5,
        max_iter=3000,
        solver="lbfgs",
        class_weight=None,
        random_state=RANDOM_STATE
    ))
])

prod_clf.fit(
    X_prod,
    y_prod,
    logreg__sample_weight=prod_sample_weight
)

# Save artifacts
joblib.dump(prod_svd, f"{ARTIFACT_DIR}/svd.joblib")
joblib.dump(prod_clf, f"{ARTIFACT_DIR}/logreg_pipeline.joblib")

metadata = {
    "embedding_model_name": EMBEDDING_MODEL_NAME,
    "n_svd_components": N_SVD_COMPONENTS,
    "confidence_threshold": 0.75,
    "labels": list(prod_clf.named_steps["logreg"].classes_),
    "random_state": RANDOM_STATE
}

with open(f"{ARTIFACT_DIR}/metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)

print("Production artifacts saved to:", ARTIFACT_DIR)
print("Classes:", prod_clf.named_steps["logreg"].classes_)

Production artifacts saved to: ../Model/logreg_artifacts
Classes: ['ideological' 'institutionalized' 'internalized' 'interpersonal']


In [26]:
# commiting from colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
%cd /content
!git clone https://github.com/ritvik-123/EMP-Project.git

/content
fatal: destination path 'EMP-Project' already exists and is not an empty directory.


In [8]:
%cd /content/EMP-Project/

/content/EMP-Project


In [33]:
!git checkout -b fastapi-deployment

Switched to a new branch 'fastapi-deployment'


In [34]:
!ls

Data			      Model			       __pycache__
Final_LogReg.ipynb	      Module_1_26.ipynb		       README.md
Generate_Gemini_Labels.ipynb  Module_1_SmallData_Rework.ipynb  requirements.txt
inference.py		      Notebook			       templates
main.py			      Notebooks			       test_api.py


In [35]:
!git status

On branch fastapi-deployment
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Data/Module 1 Sentences Gemini.csv
	modified:   Data/Module 1.csv
	modified:   Data/Module 2.csv
	modified:   Data/Module 5.csv
	modified:   Data/review_set.csv
	modified:   Data/review_set_pi.csv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Data/Generated_Sentences_1.csv
	Data/Generated_Sentences_1_1.csv
	Notebook/
	test_api.py

no changes added to commit (use "git add" and/or "git commit -a")


In [36]:
!cp /content/drive/MyDrive/EMP/main.py .
!cp /content/drive/MyDrive/EMP/inference.py .
!cp /content/drive/MyDrive/EMP/requirements.txt .
!cp /content/drive/MyDrive/EMP/.gitignore .

In [37]:
!mkdir -p templates
!cp /content/drive/MyDrive/EMP/templates/index.html templates/index.html

In [38]:
!mkdir -p Model/logreg_artifacts
!cp -r /content/drive/MyDrive/EMP/Model/logreg_artifacts/* Model/logreg_artifacts/

In [39]:
!mkdir -p Data/
!cp -r /content/drive/MyDrive/EMP/Data/* Data/
!mkdir -p Notebook/
!cp -r /content/drive/MyDrive/EMP/Notebook/* Notebook/

cp: cannot open '/content/drive/MyDrive/EMP/Data/Generated_Sentences_1.gsheet' for reading: Operation not supported


In [40]:
!git status

On branch fastapi-deployment
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Data/Module 1 Sentences Gemini.csv
	modified:   Data/Module 1.csv
	modified:   Data/Module 2.csv
	modified:   Data/Module 5.csv
	modified:   Data/review_set.csv
	modified:   Data/review_set_pi.csv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Data/Generated_Sentences_1.csv
	Data/Generated_Sentences_1_1.csv
	Notebook/
	test_api.py

no changes added to commit (use "git add" and/or "git commit -a")


In [41]:
!pip install -r requirements.txt

In [21]:
%%writefile test_api.py
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

response = client.post(
    "/predict",
    json={
        "sentence": "I started believing I was less capable because of how people treated me.",
        "use_llm_backup": False
    }
)

print("Status code:", response.status_code)
print(response.json())

Writing test_api.py


In [22]:
!python test_api.py

modules.json: 100% 349/349 [00:00<00:00, 10.5kB/s]
config_sentence_transformers.json: 100% 124/124 [00:00<00:00, 590kB/s]
README.md: 100% 94.6k/94.6k [00:00<00:00, 78.4MB/s]
sentence_bert_config.json: 100% 52.0/52.0 [00:00<00:00, 226kB/s]
config.json: 100% 779/779 [00:00<00:00, 3.67MB/s]

model.safetensors: downloading bytes:   8% 112M/1.34G [00:01<00:06, 180MB/s, 8.07MB/s  ] 
model.safetensors: downloading bytes:  19% 255M/1.34G [00:01<00:06, 176MB/s, 22.5MB/s  ]
model.safetensors: reconstructing file:  20% 268M/1.34G [00:02<00:07, 151MB/s, 6.51MB/s  ]
model.safetensors: downloading bytes:  43% 578M/1.34G [00:04<00:06, 116MB/s, 44.8MB/s  ]
model.safetensors: downloading bytes:  48% 642M/1.34G [00:04<00:07, 95.2MB/s, 48.1MB/s  ]
model.safetensors: downloading bytes:  50% 675M/1.34G [00:05<00:06, 99.1MB/s, 49.3MB/s  ]
model.safetensors: downloading bytes:  59% 787M/1.34G [00:05<00:03, 153MB/s, 55.2MB/s  ]
model.safetensors: downloading bytes:  64% 864M/1.34G [00:06<00:04, 113MB/s, 59.9M

In [42]:
!git add main.py inference.py requirements.txt .gitignore templates/index.html Model/logreg_artifacts
!git commit -m "Add FastAPI deployment for EMP classifier"

On branch fastapi-deployment
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Data/Module 1 Sentences Gemini.csv
	modified:   Data/Module 1.csv
	modified:   Data/Module 2.csv
	modified:   Data/Module 5.csv
	modified:   Data/review_set.csv
	modified:   Data/review_set_pi.csv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Data/Generated_Sentences_1.csv
	Data/Generated_Sentences_1_1.csv
	Notebook/
	test_api.py

no changes added to commit (use "git add" and/or "git commit -a")


In [43]:
!git config --global user.email "ritvik.mahapatra@yahoo.com"
!git config --global user.name "ritvik-123"

In [44]:
!git push origin fastapi-deployment

fatal: could not read Username for 'https://github.com': No such device or address


In [46]:
!git branch --show-current

fastapi-deployment


In [49]:
!git status
!git log --oneline -3

On branch fastapi-deployment
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Data/Module 1 Sentences Gemini.csv
	modified:   Data/Module 1.csv
	modified:   Data/Module 2.csv
	modified:   Data/Module 5.csv
	modified:   Data/review_set.csv
	modified:   Data/review_set_pi.csv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Data/Generated_Sentences_1.csv
	Data/Generated_Sentences_1_1.csv
	Notebook/
	test_api.py

no changes added to commit (use "git add" and/or "git commit -a")
7bcf22d (HEAD -> fastapi-deployment, fastapi-deployement) Add FastAPI deployment for EMP classifier
bb7ddb7 (origin/master, origin/HEAD, master) Saved final model trained on whole dataset
4cc205a Created using Colab


In [52]:
from getpass import getpass

token = getpass("Paste your GitHub token: ")

Paste your GitHub token: ··········


In [54]:
!git remote set-url origin https://ritvik-123:{token}@github.com/ritvik-123/EMP-Project.git

In [55]:
!git push -u origin fastapi-deployment

Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 2 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (12/12), 193.90 KiB | 4.51 MiB/s, done.
Total 12 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: 
remote: Create a pull request for 'fastapi-deployment' on GitHub by visiting:
remote:      https://github.com/ritvik-123/EMP-Project/pull/new/fastapi-deployment
remote: 
To https://github.com/ritvik-123/EMP-Project.git
 * [new branch]      fastapi-deployment -> fastapi-deployment
Branch 'fastapi-deployment' set up to track remote branch 'fastapi-deployment' from 'origin'.


In [57]:
!git status

On branch fastapi-deployment
Your branch is up to date with 'origin/fastapi-deployment'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Data/Module 1 Sentences Gemini.csv
	modified:   Data/Module 1.csv
	modified:   Data/Module 2.csv
	modified:   Data/Module 5.csv
	modified:   Data/review_set.csv
	modified:   Data/review_set_pi.csv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Data/Generated_Sentences_1.csv
	Data/Generated_Sentences_1_1.csv
	Notebook/
	test_api.py

no changes added to commit (use "git add" and/or "git commit -a")


In [58]:
!git add .
!git commit -m "Pushing everything"

[fastapi-deployment bcb9065] Pushing everything
 13 files changed, 2981 insertions(+), 1388 deletions(-)
 create mode 100644 Data/Generated_Sentences_1.csv
 create mode 100644 Data/Generated_Sentences_1_1.csv
 rewrite Data/Module 1 Sentences Gemini.csv (83%)
 create mode 100644 Notebook/Final_LogReg.ipynb
 create mode 100644 Notebook/Generate Gemini Labels.ipynb
 create mode 100644 Notebook/Module 1-26.ipynb
 create mode 100644 Notebook/Module_1_SmallData_Rework.ipynb
 create mode 100644 test_api.py


In [59]:
!git push origin fastapi-deployment

Enumerating objects: 25, done.
Counting objects: 100% (25/25), done.
Delta compression using up to 2 threads
Compressing objects: 100% (17/17), done.
Writing objects: 100% (17/17), 136.55 KiB | 2.73 MiB/s, done.
Total 17 (delta 10), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (10/10), completed with 7 local objects.
To https://github.com/ritvik-123/EMP-Project.git
   7bcf22d..bcb9065  fastapi-deployment -> fastapi-deployment
